SELECT * FROM INGRESOS
WHERE MONTH(ING_FECHA_ALTA) = 12 AND YEAR(ING_FECHA_ALTA) = 2011
;

-- Reporte del ingreso por mes
SELECT MONTH(ING_FECHA_INGRESO) AS MES, SUM(ING_IMPORTE) AS IMPORTE FROM INGRESOS
WHERE MONTH(ING_FECHA_ALTA) = 12 AND YEAR(ING_FECHA_ALTA) = 2011
GROUP BY MONTH(ING_FECHA_INGRESO);


-- Reporte de egresos por mes
SELECT CE.CATE_DESCRIPCION, SUM(EGR_IMPORTE) AS IMPORTE FROM EGRESOS E 
INNER JOIN CATALOGO_EGRESOS CE ON E.CATE_ID = CE.CATE_ID 
WHERE MONTH(EGR_FECHA_EGRESO) = 12 AND YEAR(EGR_FECHA_EGRESO) = 2011
GROUP BY CE.CATE_ID;

SELECT * FROM EGRESOS;


-- Reporte de las personas que han pagado

SELECT
    *
FROM
    CONDOMINOS C LEFT JOIN (
        SELECT *
        FROM INGRESOS 
        WHERE MONTH(ING_FECHA_INGRESO) = 12 AND YEAR(ING_FECHA_INGRESO) = 2011)
    INGRESOS USING (COND_ID)
    JOIN USUARIO USING (USR_ID);





-- Reporte Ingreso con descripcion

SELECT MONTH(I.ING_FECHA_INGRESO) AS MES, CI.CATI_DESCRIPCION, SUM(I.ING_IMPORTE) AS IMPORTE FROM INGRESOS I 
INNER JOIN CATALOGO_INGRESOS CI ON I.CATI_ID = CI.CATI_ID
WHERE MONTH(ING_FECHA_ALTA) = 12 AND YEAR(ING_FECHA_ALTA) = 2011
GROUP BY MONTH(ING_FECHA_INGRESO), CI.CATI_ID ;



SELECT
    C.COND_NUM_CASA, USR_NOMBRE 
FROM
    CONDOMINOS C LEFT JOIN (
        SELECT *
        FROM INGRESOS
        WHERE  MONTH(ING_FECHA_INGRESO) = 11 AND YEAR(ING_FECHA_INGRESO) = 2011)
    I USING (COND_ID)
    JOIN USUARIO USING (USR_ID);
    
    
    ---- Para obtener a los deudores de un tiempo definido
    SELECT
    C.COND_NUM_CASA, IFNULL(USR_NOMBRE, '-- SIN NOMBRE --') AS NOMBRE, IFNULL(ING_FECHA_INGRESO, '--------'), IFNULL(ING_IMPORTE, '0.00')
FROM
    CONDOMINOS C LEFT JOIN (
        SELECT *
        FROM INGRESOS
        WHERE DATEDIFF(ING_FECHA_INGRESO, '2011-11-01') >0 AND DATEDIFF(ING_FECHA_INGRESO, '2011-12-31') < 0
    )
    I USING (COND_ID)
    JOIN USUARIO USING (USR_ID);

